#!/bin/sh -e

. scripts/lib.sh
if [ "$CC" != "" ]; then cc="$CC"; else . scripts/cc-pick.sh; fi
. scripts/cc-target.sh
. scripts/cc-conf.sh

# Manage expectations!
case "$target_os" in
	linux) ;;
	macos)
		warn "warning: macOS is known to be a really BAD Unix implementation!"
		warn "         it is also currently totally untested - expect issues!" ;;
	unknown)
		warn "warning: build is not tested on your OS, so you may have issues..."
		warn "* let me know how it goes! *" ;;
	*)
		warn "heads up: this OS is yet to be tested, but should work in theory."
		warn "* let me know how you get on! *" ;;
esac

cflags="-O3 -Wall -Wno-parentheses -Wno-missing-braces -Wno-misleading-indentation -fpic"
ldflags="-O3 -fpic -fpie -s"
test_cflags=

if is_cmd cpoly-config; then
	cpoly_cflags="`cpoly-config`"
	cpoly_ldflags=-lcpoly
else
	warn "error: couldn't find libcpoly installation (libc compatibility layer)"
	warn "unless you're using an OS that doesn't exist yet, install this:"
	warn "  https://gitlab.com/mikesmiffy128/libcpoly"
	exit 1
fi

if echo "__attribute__((constructor)) void x(void) {}" | \
		$cc -c -x c -o /dev/null - 2>/dev/null; then
	do_tests=1
else
	warn "warning: compiler does not appear to like __attribute__((constructor))"
	warn "warning: automated tests will not be built, so don't break anything!"
	do_tests=0
fi

mkdir -p build/strap/bin build/strap/lib

# XXX could compile separate objects in parallel, I *guess*, but building hardly
# takes long anyway so not a high priority
# XXX could also at least reuse objects, that might be more worthwhile, idunno
num_items=4 # ← remember to change this manually
is_tty && printf "[0/$num_items] build" || :
$cc $cflags $extra_cflags $cpoly_cflags $ldflags $extra_ldflags -fpie $cpoly_ldflags \
-Icbits/include \
src/blake2b.c \
src/build.c \
src/evloop.c \
src/fpath.c \
src/fd.c \
src/infile.c \
src/proc.c \
src/sigstr.c \
src/task.c \
src/time.c \
src/tui.c \
cbits/src/errorstring.c \
cbits/src/errmsg.c \
cbits/src/fmt.c \
cbits/src/iobuf.c \
cbits/src/path.c \
-o build/strap/bin/build

is_tty && printf "\r[K[1/$num_items] build-dep" || :
$cc $cflags $extra_cflags $cpoly_cflags $ldflags $extra_ldflags -fpie $cpoly_ldflags \
-Icbits/include \
src/build-dep.c \
cbits/src/errorstring.c \
cbits/src/errmsg.c \
cbits/src/iobuf.c \
-o build/strap/bin/build-dep

is_tty && printf "\r[K[2/$num_items] build-infile" || :
$cc $cflags $extra_cflags $cpoly_cflags $ldflags $extra_ldflags -fpie $cpoly_ldflags \
-Icbits/include \
src/build-infile.c \
cbits/src/errorstring.c \
cbits/src/errmsg.c \
cbits/src/iobuf.c \
-o build/strap/bin/build-infile

is_tty && printf "\r[K[3/$num_items] libbuild" || :
$cc -shared $cflags $extra_cflags $cpoly_cflags $ldflags $extra_ldflags $cpoly_ldflags \
-Icbits/include \
src/libbuild.c \
-o build/strap/lib/libbuild.so

is_tty && printf "\r[K" || :

# vi: sw=4 ts=4 noet tw=80 cc=80
