#!/bin/sh -e
# This file is dedicated to the public domain.

exec >compile_commands.json

put_entry() {
	cat <<EOF
	{
		"directory": ".",
		"file": "$1",
		"command": "clang -c -Wall -pedantic -Wno-parentheses -fparse-all-comments -Icbits/include `cpoly-config`$3 \"$1\""
	}$2
EOF
}

count_entries() { nents=$#; }

put_entries() {
	for _s in "$@"; do
		nents=$(($nents-1))
		_sep=","
		if [ $nents = 0 ]; then _sep=""; fi
		extra=
		# just use latest lua in order to have _something_
		if [ "$_s" = "src/lbuild.c" ]; then
			extra=" -DLUA_HEADER=<lua.h> -DLUA_AUX_HEADER=<lauxlib.h>";
		fi
		put_entry "$_s" "$_sep" "$extra"
	done
}
echo [
count_entries src/*.c
put_entries src/*.c
echo ]

# vi: sw=4 ts=4 noet tw=80 cc=80
